// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>VONAPP_0000_ObjectMap_Helper</b><br>
 * Generated     : <b>2011/08/16 2:22:55 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  August 16, 2011
 * @author 281MGOTT
 */
public abstract class VONAPP_0000_ObjectMap_HelperHelper extends RationalTestScript
{
	/**
	 * LogOnsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log On
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_LoginSubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_LoginSubmit"));
	}
	/**
	 * LogOnsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log On
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_LoginSubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_LoginSubmit"), anchor, flags);
	}
	
	/**
	 * AcceptedAccepted_terms_Condition: with default state.
	 *		.id : accept_1
	 * 		.type : checkbox
	 * 		.value : Accepted_terms_Condition
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : Accepted
	 * 		.classIndex : 0
	 */
	public ToggleGUITestObject checkBox_acceptedAccepted_term() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_acceptedAccepted_term"));
	}
	/**
	 * AcceptedAccepted_terms_Condition: with specific test context and state.
	 *		.id : accept_1
	 * 		.type : checkbox
	 * 		.value : Accepted_terms_Condition
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : Accepted
	 * 		.classIndex : 0
	 */
	public ToggleGUITestObject checkBox_acceptedAccepted_term(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_acceptedAccepted_term"), anchor, flags);
	}
	
	/**
	 * eBenefitsHome: with default state.
	 *		.title : eBenefits - Home
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://.*\..*\.va\.gov/ebenefits-portal*
	 */
	public DocumentTestObject document_eBenefitsHome() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_eBenefitsHome"));
	}
	/**
	 * eBenefitsHome: with specific test context and state.
	 *		.title : eBenefits - Home
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://.*\..*\.va\.gov/ebenefits-portal*
	 */
	public DocumentTestObject document_eBenefitsHome(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_eBenefitsHome"), anchor, flags);
	}
	
	/**
	 * ApplyForDependentBenefits: with default state.
	 *		.text : Apply for Dependent Benefits >
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId=newDepend ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_applyForDependentBenefits() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_applyForDependentBenefits"));
	}
	/**
	 * ApplyForDependentBenefits: with specific test context and state.
	 *		.text : Apply for Dependent Benefits >
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId=newDepend ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_applyForDependentBenefits(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_applyForDependentBenefits"), anchor, flags);
	}
	
	/**
	 * btnBack: with default state.
	 *		.text : Previous
	 * 		.id : btnBack
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s3&_eventId_previous
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_btnPrevious() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_btnPrevious"));
	}
	/**
	 * btnBack: with specific test context and state.
	 *		.text : Previous
	 * 		.id : btnBack
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s3&_eventId_previous
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_btnPrevious(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_btnPrevious"), anchor, flags);
	}
	
	/**
	 * btnNext: with default state.
	 *		.text : Save & Continue
	 * 		.id : btnNext
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s3&_eventId_continue
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_btnSubmitAndContinue() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_btnSubmitAndContinue"));
	}
	/**
	 * btnNext: with specific test context and state.
	 *		.text : Save & Continue
	 * 		.id : btnNext
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s3&_eventId_continue
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_btnSubmitAndContinue(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_btnSubmitAndContinue"), anchor, flags);
	}
	
	/**
	 * Dashboard: with default state.
	 *		.text : Dashboard
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_dashboard() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_dashboard"));
	}
	/**
	 * Dashboard: with specific test context and state.
	 *		.text : Dashboard
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_dashboard(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_dashboard"), anchor, flags);
	}
	
	/**
	 * LogIn: with default state.
	 *		.text : Log In
	 * 		.id : 
	 * 		.href : https://pint.ebenefits.va.gov/ebenefits-portal/ebenefits.portal/dsLogon.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_logIn() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logIn"));
	}
	/**
	 * LogIn: with specific test context and state.
	 *		.text : Log In
	 * 		.id : 
	 * 		.href : https://pint.ebenefits.va.gov/ebenefits-portal/ebenefits.portal/dsLogon.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_logIn(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logIn"), anchor, flags);
	}
	
	/**
	 * LogOut: with default state.
	 *		.text : Log Out
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal/logout.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_logOut() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logOut"));
	}
	/**
	 * LogOut: with specific test context and state.
	 *		.text : Log Out
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal/logout.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_logOut(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logOut"), anchor, flags);
	}
	
	/**
	 * MyEBenefits: with default state.
	 *		.text : My eBenefits
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_myEBenefits() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_myEBenefits"));
	}
	/**
	 * MyEBenefits: with specific test context and state.
	 *		.text : My eBenefits
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_myEBenefits(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_myEBenefits"), anchor, flags);
	}
	
	/**
	 * submitANewApplication: with default state.
	 *		.text : submit a new application
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId=newDepend ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_submitANewApplication() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_submitANewApplication"));
	}
	/**
	 * submitANewApplication: with specific test context and state.
	 *		.text : submit a new application
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId=newDepend ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_submitANewApplication(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_submitANewApplication"), anchor, flags);
	}
	
	/**
	 * VeteransOnlineApplicationVONAPPDirectConnect: with default state.
	 *		.text : Veterans Online Application (VONAPP) Direct Connect
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 20
	 */
	public GuiTestObject link_veteransOnlineApplication() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_veteransOnlineApplication"));
	}
	/**
	 * VeteransOnlineApplicationVONAPPDirectConnect: with specific test context and state.
	 *		.text : Veterans Online Application (VONAPP) Direct Connect
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 20
	 */
	public GuiTestObject link_veteransOnlineApplication(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_veteransOnlineApplication"), anchor, flags);
	}
	
	/**
	 * famId: with default state.
	 *		.id : famId
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : famId
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_loginId() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_loginId"));
	}
	/**
	 * famId: with specific test context and state.
	 *		.id : famId
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : famId
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_loginId(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_loginId"), anchor, flags);
	}
	
	/**
	 * pwd: with default state.
	 *		.id : pwd
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_pwd() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"));
	}
	/**
	 * pwd: with specific test context and state.
	 *		.id : pwd
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_pwd(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"), anchor, flags);
	}
	
	

	protected VONAPP_0000_ObjectMap_HelperHelper()
	{
		setScriptName("TestScripts.VONAPP_0000_ObjectMap_Helper");
	}
	
}

