// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>VONAPP_0000_ObjectMap_Helper</b><br>
 * Generated     : <b>2011/08/22 2:36:56 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  August 22, 2011
 * @author Bhavna Vyas
 */
public abstract class VONAPP_0000_ObjectMap_HelperHelper extends RationalTestScript
{
	/**
	 * LogOnsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log On
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_LoginSubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_LoginSubmit"));
	}
	/**
	 * LogOnsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log On
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_LoginSubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_LoginSubmit"), anchor, flags);
	}
	
	/**
	 * AcceptedAccepted_terms_Condition: with default state.
	 *		.id : accept_1
	 * 		.type : checkbox
	 * 		.value : Accepted_terms_Condition
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : Accepted
	 * 		.classIndex : 0
	 */
	public ToggleGUITestObject checkBox_acceptedAccepted_term() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_acceptedAccepted_term"));
	}
	/**
	 * AcceptedAccepted_terms_Condition: with specific test context and state.
	 *		.id : accept_1
	 * 		.type : checkbox
	 * 		.value : Accepted_terms_Condition
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : Accepted
	 * 		.classIndex : 0
	 */
	public ToggleGUITestObject checkBox_acceptedAccepted_term(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_acceptedAccepted_term"), anchor, flags);
	}
	
	/**
	 * eBenefitsHome: with default state.
	 *		.title : eBenefits - Home
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://.*\..*\.va\.gov/ebenefits-portal*
	 */
	public DocumentTestObject document_eBenefitsHome() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_eBenefitsHome"));
	}
	/**
	 * eBenefitsHome: with specific test context and state.
	 *		.title : eBenefits - Home
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://.*\..*\.va\.gov/ebenefits-portal*
	 */
	public DocumentTestObject document_eBenefitsHome(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_eBenefitsHome"), anchor, flags);
	}
	
	/**
	 * contactTheVA: with default state.
	 *		.text : contact the VA
	 * 		.id : 
	 * 		.href : RegularExpression(https://www\.ebenefits\.va\.gov/ebenefits-portal/ebenefits\.po ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	public GuiTestObject link_ContactTheVA() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_ContactTheVA"));
	}
	/**
	 * contactTheVA: with specific test context and state.
	 *		.text : contact the VA
	 * 		.id : 
	 * 		.href : RegularExpression(https://www\.ebenefits\.va\.gov/ebenefits-portal/ebenefits\.po ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	public GuiTestObject link_ContactTheVA(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_ContactTheVA"), anchor, flags);
	}
	
	/**
	 * Continue: with default state.
	 *		.text : Continue
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId_continueO ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	public GuiTestObject link_Continue() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_Continue"));
	}
	/**
	 * Continue: with specific test context and state.
	 *		.text : Continue
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId_continueO ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	public GuiTestObject link_Continue(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_Continue"), anchor, flags);
	}
	
	/**
	 * DeleteMANAGEDEPENDENTSCreatedAug172011: with default state.
	 *		.text : Delete MANAGEDEPENDENTS Created Aug 17, 2011
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId_deleteOpe ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	public GuiTestObject link_Delete() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_Delete"));
	}
	/**
	 * DeleteMANAGEDEPENDENTSCreatedAug172011: with specific test context and state.
	 *		.text : Delete MANAGEDEPENDENTS Created Aug 17, 2011
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId_deleteOpe ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	public GuiTestObject link_Delete(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_Delete"), anchor, flags);
	}
	
	/**
	 * Help: with default state.
	 *		.text : Help
	 * 		.href : https://pint.ebenefits.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 29
	 */
	public GuiTestObject link_Help() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_Help"));
	}
	/**
	 * Help: with specific test context and state.
	 *		.text : Help
	 * 		.href : https://pint.ebenefits.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 29
	 */
	public GuiTestObject link_Help(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_Help"), anchor, flags);
	}
	
	/**
	 * ManageDependents: with default state.
	 *		.text : Manage Dependents
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId_continueO ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	public GuiTestObject link_ManageDependents() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_ManageDependents"));
	}
	/**
	 * ManageDependents: with specific test context and state.
	 *		.text : Manage Dependents
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId_continueO ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	public GuiTestObject link_ManageDependents(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_ManageDependents"), anchor, flags);
	}
	
	/**
	 * ApplicationType: with default state.
	 *		.text : Application Type
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do;VNP_JSESSIONID=5T5ZTNlpZXQ9KkZvq1 ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_applicationType() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_applicationType"));
	}
	/**
	 * ApplicationType: with specific test context and state.
	 *		.text : Application Type
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do;VNP_JSESSIONID=5T5ZTNlpZXQ9KkZvq1 ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_applicationType(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_applicationType"), anchor, flags);
	}
	
	/**
	 * ApplyForDependentBenefits: with default state.
	 *		.text : Apply for Dependent Benefits >
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId=newDepend ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_applyForDependentBenefits() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_applyForDependentBenefits"));
	}
	/**
	 * ApplyForDependentBenefits: with specific test context and state.
	 *		.text : Apply for Dependent Benefits >
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId=newDepend ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_applyForDependentBenefits(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_applyForDependentBenefits"), anchor, flags);
	}
	
	/**
	 * btnBack: with default state.
	 *		.text : Previous
	 * 		.id : btnBack
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s3&_eventId_previous
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_btnPrevious() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_btnPrevious"));
	}
	/**
	 * btnBack: with specific test context and state.
	 *		.text : Previous
	 * 		.id : btnBack
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s3&_eventId_previous
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_btnPrevious(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_btnPrevious"), anchor, flags);
	}
	
	/**
	 * btnNext: with default state.
	 *		.text : Save & Continue
	 * 		.id : btnNext
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s3&_eventId_continue
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_btnSubmitAndContinue() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_btnSubmitAndContinue"));
	}
	/**
	 * btnNext: with specific test context and state.
	 *		.text : Save & Continue
	 * 		.id : btnNext
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s3&_eventId_continue
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_btnSubmitAndContinue(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_btnSubmitAndContinue"), anchor, flags);
	}
	
	/**
	 * Dashboard: with default state.
	 *		.text : Dashboard
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_dashboard() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_dashboard"));
	}
	/**
	 * Dashboard: with specific test context and state.
	 *		.text : Dashboard
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_dashboard(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_dashboard"), anchor, flags);
	}
	
	/**
	 * LogIn: with default state.
	 *		.text : Log In
	 * 		.id : 
	 * 		.href : https://pint.ebenefits.va.gov/ebenefits-portal/ebenefits.portal/dsLogon.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_logIn() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logIn"));
	}
	/**
	 * LogIn: with specific test context and state.
	 *		.text : Log In
	 * 		.id : 
	 * 		.href : https://pint.ebenefits.va.gov/ebenefits-portal/ebenefits.portal/dsLogon.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_logIn(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logIn"), anchor, flags);
	}
	
	/**
	 * LogOut: with default state.
	 *		.text : Log Out
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal/logout.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_logOut() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logOut"));
	}
	/**
	 * LogOut: with specific test context and state.
	 *		.text : Log Out
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal/logout.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_logOut(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logOut"), anchor, flags);
	}
	
	/**
	 * MyEBenefits: with default state.
	 *		.text : My eBenefits
	 * 		.href : RegularExpression(https://.*va\.gov/ebenefits-portal.*)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_myEBenefits() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_myEBenefits"));
	}
	/**
	 * MyEBenefits: with specific test context and state.
	 *		.text : My eBenefits
	 * 		.href : RegularExpression(https://.*va\.gov/ebenefits-portal.*)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_myEBenefits(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_myEBenefits"), anchor, flags);
	}
	
	/**
	 * submitANewApplication: with default state.
	 *		.text : submit a new application
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId=newDepend ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_submitANewApplication() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_submitANewApplication"));
	}
	/**
	 * submitANewApplication: with specific test context and state.
	 *		.text : submit a new application
	 * 		.id : 
	 * 		.href : https://test.eauth.va.gov/VONAPP2/dashboard.do?execution=e1s1&_eventId=newDepend ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_submitANewApplication(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_submitANewApplication"), anchor, flags);
	}
	
	/**
	 * VeteransOnlineApplicationVONAPPDirectConnect: with default state.
	 *		.text : Veterans Online Application (VONAPP) Direct Connect
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 20
	 */
	public GuiTestObject link_veteransOnlineApplication() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_veteransOnlineApplication"));
	}
	/**
	 * VeteransOnlineApplicationVONAPPDirectConnect: with specific test context and state.
	 *		.text : Veterans Online Application (VONAPP) Direct Connect
	 * 		.href : https://test.eauth.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=fal ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 20
	 */
	public GuiTestObject link_veteransOnlineApplication(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_veteransOnlineApplication"), anchor, flags);
	}
	
	/**
	 * ManageDependentsVONAPPII: with default state.
	 *		.text : Manage Dependents (VONAPP II)
	 * 		.href : javascript:bea.wlp.disc.xie._Service.update('https://test.eauth.va.gov/ebenefits ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject tab_ManageDependentsVONAPPII() 
	{
		return new GuiTestObject(
                        getMappedTestObject("tab_ManageDependentsVONAPPII"));
	}
	/**
	 * ManageDependentsVONAPPII: with specific test context and state.
	 *		.text : Manage Dependents (VONAPP II)
	 * 		.href : javascript:bea.wlp.disc.xie._Service.update('https://test.eauth.va.gov/ebenefits ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject tab_ManageDependentsVONAPPII(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("tab_ManageDependentsVONAPPII"), anchor, flags);
	}
	
	/**
	 * ApplicationTypeCreatedLastUpdatedLastOpenedExpires: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	public StatelessGuiSubitemTestObject table_OpenApplications() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_OpenApplications"));
	}
	/**
	 * ApplicationTypeCreatedLastUpdatedLastOpenedExpires: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	public StatelessGuiSubitemTestObject table_OpenApplications(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_OpenApplications"), anchor, flags);
	}
	
	/**
	 * ApplicationTypeCreatedLastUpdatedExpiresSubmitted: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	public StatelessGuiSubitemTestObject table_SubmittedApplications() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_SubmittedApplications"));
	}
	/**
	 * ApplicationTypeCreatedLastUpdatedExpiresSubmitted: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	public StatelessGuiSubitemTestObject table_SubmittedApplications(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_SubmittedApplications"), anchor, flags);
	}
	
	/**
	 * famId: with default state.
	 *		.id : famId
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : famId
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_loginId() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_loginId"));
	}
	/**
	 * famId: with specific test context and state.
	 *		.id : famId
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : famId
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_loginId(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_loginId"), anchor, flags);
	}
	
	/**
	 * pwd: with default state.
	 *		.id : pwd
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_pwd() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"));
	}
	/**
	 * pwd: with specific test context and state.
	 *		.id : pwd
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_pwd(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"), anchor, flags);
	}
	
	

	protected VONAPP_0000_ObjectMap_HelperHelper()
	{
		setScriptName("TestScripts.VONAPP_0000_ObjectMap_Helper");
	}
	
}

