// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts;
import FuncLib.HelpUtil;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>EB_0000_ObjectMap_Helper</b><br>
 * Generated     : <b>2011/09/20 2:03:21 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  September 20, 2011
 * @author imcva
 */
public abstract class EB_0000_ObjectMap_HelperHelper extends FuncLib.HelpUtil
{
	/**
	 * Calculatesubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Calculate
	 * 		.title : Calculate
	 * 		.class : Html.INPUT.submit
	 * 		.name : action
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_calculatesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_calculatesubmit"));
	}
	/**
	 * Calculatesubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Calculate
	 * 		.title : Calculate
	 * 		.class : Html.INPUT.submit
	 * 		.name : action
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_calculatesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_calculatesubmit"), anchor, flags);
	}
	
	/**
	 * LogOnsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log On
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_logOnsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logOnsubmit"));
	}
	/**
	 * LogOnsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log On
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_logOnsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logOnsubmit"), anchor, flags);
	}
	
	/**
	 * Loginbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Login
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_loginbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_loginbutton"));
	}
	/**
	 * Loginbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Login
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_loginbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_loginbutton"), anchor, flags);
	}
	
	/**
	 * Logoutbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Logout
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logout"));
	}
	/**
	 * Logoutbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Logout
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logout"), anchor, flags);
	}
	
	/**
	 * Resetbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Reset
	 * 		.title : reset
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_resetbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_resetbutton"));
	}
	/**
	 * Resetbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Reset
	 * 		.title : reset
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_resetbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_resetbutton"), anchor, flags);
	}
	
	/**
	 * DMDCErrorPage: with default state.
	 *		.text : DMDC Error Page Sorry!! Application is not available.
	 * 		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_CivilianInfo_dmdcErrorPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_CivilianInfo_dmdcErrorPage"));
	}
	/**
	 * DMDCErrorPage: with specific test context and state.
	 *		.text : DMDC Error Page Sorry!! Application is not available.
	 * 		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_CivilianInfo_dmdcErrorPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_CivilianInfo_dmdcErrorPage"), anchor, flags);
	}
	
	/**
	 * DMDCErrorPage: with default state.
	 *		.text : DMDC Error Page Sorry!! Application is not available.
	 * 		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://test.eauth.va.gov/ebenefits-portal/portlets/dmdc/dmdc_v2_giqd_beneficiar ...
	 */
	public DocumentTestObject document_DOD_dmdcErrorPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_DOD_dmdcErrorPage"));
	}
	/**
	 * DMDCErrorPage: with specific test context and state.
	 *		.text : DMDC Error Page Sorry!! Application is not available.
	 * 		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://test.eauth.va.gov/ebenefits-portal/portlets/dmdc/dmdc_v2_giqd_beneficiar ...
	 */
	public DocumentTestObject document_DOD_dmdcErrorPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_DOD_dmdcErrorPage"), anchor, flags);
	}
	
	/**
	 * DMDCErrorPage: with default state.
	 *		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_MRRI_dmdcErrorPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_MRRI_dmdcErrorPage"));
	}
	/**
	 * DMDCErrorPage: with specific test context and state.
	 *		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_MRRI_dmdcErrorPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_MRRI_dmdcErrorPage"), anchor, flags);
	}
	
	/**
	 * DMDCErrorPage: with default state.
	 *		.text : DMDC Error Page Sorry!! Application is not available.
	 * 		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_SGLI_dmdcErrorPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_SGLI_dmdcErrorPage"));
	}
	/**
	 * DMDCErrorPage: with specific test context and state.
	 *		.text : DMDC Error Page Sorry!! Application is not available.
	 * 		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_SGLI_dmdcErrorPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_SGLI_dmdcErrorPage"), anchor, flags);
	}
	
	/**
	 * DMDCErrorPage: with default state.
	 *		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_SMPI_dmdcErrorPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_SMPI_dmdcErrorPage"));
	}
	/**
	 * DMDCErrorPage: with specific test context and state.
	 *		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_SMPI_dmdcErrorPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_SMPI_dmdcErrorPage"), anchor, flags);
	}
	
	/**
	 * AgentOrangeFastTrackClaimsProcessingSystem: with default state.
	 *		.title : Agent Orange Fast Track Claims Processing System
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.fasttrack.va.gov/AOFastTrack/help3.do
	 */
	public DocumentTestObject document_agentOrangeFastTrackC() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_agentOrangeFastTrackC"));
	}
	/**
	 * AgentOrangeFastTrackClaimsProcessingSystem: with specific test context and state.
	 *		.title : Agent Orange Fast Track Claims Processing System
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.fasttrack.va.gov/AOFastTrack/help3.do
	 */
	public DocumentTestObject document_agentOrangeFastTrackC(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_agentOrangeFastTrackC"), anchor, flags);
	}
	
	/**
	 * DMDCErrorPage: with default state.
	 *		.text : DMDC Error Page Sorry!! Application is not available.
	 * 		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_ccd_dmdcErrorPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ccd_dmdcErrorPage"));
	}
	/**
	 * DMDCErrorPage: with specific test context and state.
	 *		.text : DMDC Error Page Sorry!! Application is not available.
	 * 		.title : DMDC Error Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https:/.*.va\.gov/ebenefits-portal/portlets/dmdc/.*)
	 */
	public DocumentTestObject document_ccd_dmdcErrorPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ccd_dmdcErrorPage"), anchor, flags);
	}
	
	/**
	 * eBenefitsApply: with default state.
	 *		.title : RegularExpression(eBenefits.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://.*.va\.gov/ebenefits-portal.*)
	 */
	public DocumentTestObject document_eBenefitsHome() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_eBenefitsHome"));
	}
	/**
	 * eBenefitsApply: with specific test context and state.
	 *		.title : RegularExpression(eBenefits.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://.*.va\.gov/ebenefits-portal.*)
	 */
	public DocumentTestObject document_eBenefitsHome(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_eBenefitsHome"), anchor, flags);
	}
	
	/**
	 * InternetExplorerCannotDisplayTheWebpage: with default state.
	 *		.title : Internet Explorer cannot display the webpage
	 * 		.class : Html.HtmlDocument
	 * 		.url : res://ieframe.dll/dnserror.htm#https://test.eauth.va.gov/FIM/sps/saml11fed_CSP/s ...
	 */
	public DocumentTestObject document_internetExplorerCanno() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_internetExplorerCanno"));
	}
	/**
	 * InternetExplorerCannotDisplayTheWebpage: with specific test context and state.
	 *		.title : Internet Explorer cannot display the webpage
	 * 		.class : Html.HtmlDocument
	 * 		.url : res://ieframe.dll/dnserror.htm#https://test.eauth.va.gov/FIM/sps/saml11fed_CSP/s ...
	 */
	public DocumentTestObject document_internetExplorerCanno(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_internetExplorerCanno"), anchor, flags);
	}
	
	/**
	 * SGLIError: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://.*\.va\.gov/ebenefits-portal/portlets.*)
	 */
	public DocumentTestObject document_sgliError() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_sgliError"));
	}
	/**
	 * SGLIError: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://.*\.va\.gov/ebenefits-portal/portlets.*)
	 */
	public DocumentTestObject document_sgliError(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_sgliError"), anchor, flags);
	}
	
	/**
	 * VetEmplSearch: with default state.
	 *		.title : RegularExpression(.*VA E-Authentication)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://www\.va\.gov/EAUTH/.*)
	 */
	public DocumentTestObject document_vetEmplSearch() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_vetEmplSearch"));
	}
	/**
	 * VetEmplSearch: with specific test context and state.
	 *		.title : RegularExpression(.*VA E-Authentication)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://www\.va\.gov/EAUTH/.*)
	 */
	public DocumentTestObject document_vetEmplSearch(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_vetEmplSearch"), anchor, flags);
	}
	
	/**
	 * CompPensionStError: with default state.
	 *		.id : RegularExpression(disc.*)
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject html_compPensionStError() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_compPensionStError"));
	}
	/**
	 * CompPensionStError: with specific test context and state.
	 *		.id : RegularExpression(disc.*)
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject html_compPensionStError(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_compPensionStError"), anchor, flags);
	}
	
	/**
	 * skip: with default state.
	 *		.text : Specially Adapted Housing Grant Application and Claim Status
	 * 		.id : skip
	 * 		.title : 
	 * 		.class : Html.H1
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_SplAdaptedHousingGrantAppl() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_SplAdaptedHousingGrantAppl"));
	}
	/**
	 * skip: with specific test context and state.
	 *		.text : Specially Adapted Housing Grant Application and Claim Status
	 * 		.id : skip
	 * 		.title : 
	 * 		.class : Html.H1
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_SplAdaptedHousingGrantAppl(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_SplAdaptedHousingGrantAppl"), anchor, flags);
	}
	
	/**
	 * skip: with default state.
	 *		.id : skip
	 * 		.title : 
	 * 		.class : Html.H1
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_TransferPost911GIBillEducationBenefits() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_TransferPost911GIBillEducationBenefits"));
	}
	/**
	 * skip: with specific test context and state.
	 *		.id : skip
	 * 		.title : 
	 * 		.class : Html.H1
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_TransferPost911GIBillEducationBenefits(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_TransferPost911GIBillEducationBenefits"), anchor, flags);
	}
	
	/**
	 * ErrorAndContact: with default state.
	 *		.id : main_content
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_VAErrorAndContact() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_VAErrorAndContact"));
	}
	/**
	 * ErrorAndContact: with specific test context and state.
	 *		.id : main_content
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_VAErrorAndContact(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_VAErrorAndContact"), anchor, flags);
	}
	
	/**
	 * CompPensionError: with default state.
	 *		.id : RegularExpression(disc.*)
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_compPensionError() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_compPensionError"));
	}
	/**
	 * CompPensionError: with specific test context and state.
	 *		.id : RegularExpression(disc.*)
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_compPensionError(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_compPensionError"), anchor, flags);
	}
	
	/**
	 * DODHealthCareError: with default state.
	 *		.text : DoD Health Insurance Information
	 * 		.id : portlet-HCI
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_dodHealthCareError() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_dodHealthCareError"));
	}
	/**
	 * DODHealthCareError: with specific test context and state.
	 *		.text : DoD Health Insurance Information
	 * 		.id : portlet-HCI
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_dodHealthCareError(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_dodHealthCareError"), anchor, flags);
	}
	
	/**
	 * FedIndRecFIRP: with default state.
	 *		.id : skip
	 * 		.title : 
	 * 		.class : Html.H1
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_fedIndRecFIRP() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_fedIndRecFIRP"));
	}
	/**
	 * FedIndRecFIRP: with specific test context and state.
	 *		.id : skip
	 * 		.title : 
	 * 		.class : Html.H1
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_fedIndRecFIRP(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_fedIndRecFIRP"), anchor, flags);
	}
	
	/**
	 * IEPageFailure: with default state.
	 *		.id : mainTitle
	 * 		.title : 
	 * 		.class : Html.H1
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_iEcannotDisplay() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_iEcannotDisplay"));
	}
	/**
	 * IEPageFailure: with specific test context and state.
	 *		.id : mainTitle
	 * 		.title : 
	 * 		.class : Html.H1
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_iEcannotDisplay(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_iEcannotDisplay"), anchor, flags);
	}
	
	/**
	 * lblSGLI: with default state.
	 *		.id : RegularExpression(disc.*)
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_lblSGLI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_lblSGLI"));
	}
	/**
	 * lblSGLI: with specific test context and state.
	 *		.id : RegularExpression(disc.*)
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_lblSGLI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_lblSGLI"), anchor, flags);
	}
	
	/**
	 * VetEmplSearchPageText: with default state.
	 *		.id : content-area-template-B
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_vetEmplSearchPageText() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_vetEmplSearchPageText"));
	}
	/**
	 * VetEmplSearchPageText: with specific test context and state.
	 *		.id : content-area-template-B
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_vetEmplSearchPageText(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_vetEmplSearchPageText"), anchor, flags);
	}
	
	/**
	 * welcome: with default state.
	 *		.text : RegularExpression(Welcome.*)
	 * 		.className : welcome
	 * 		.class : Html.DIV
	 */
	public GuiTestObject lbl_welcomeTag() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_welcomeTag"));
	}
	/**
	 * welcome: with specific test context and state.
	 *		.text : RegularExpression(Welcome.*)
	 * 		.className : welcome
	 * 		.class : Html.DIV
	 */
	public GuiTestObject lbl_welcomeTag(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_welcomeTag"), anchor, flags);
	}
	
	/**
	 * DiagnoseConnectionProblems: with default state.
	 *		.text : Diagnose Connection Problems
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_diagnoseConnectionProblem() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_diagnoseConnectionProblem"));
	}
	/**
	 * DiagnoseConnectionProblems: with specific test context and state.
	 *		.text : Diagnose Connection Problems
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_diagnoseConnectionProblem(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_diagnoseConnectionProblem"), anchor, flags);
	}
	
	/**
	 * famId: with default state.
	 *		.id : famId
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : famId
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_LogInID() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_LogInID"));
	}
	/**
	 * famId: with specific test context and state.
	 *		.id : famId
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : famId
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_LogInID(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_LogInID"), anchor, flags);
	}
	
	/**
	 * fullName: with default state.
	 *		.id : fullName
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : fullName
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_fullName() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_fullName"));
	}
	/**
	 * fullName: with specific test context and state.
	 *		.id : fullName
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : fullName
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_fullName(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_fullName"), anchor, flags);
	}
	
	/**
	 * pwd: with default state.
	 *		.id : pwd
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_pwd() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"));
	}
	/**
	 * pwd: with specific test context and state.
	 *		.id : pwd
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_pwd(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"), anchor, flags);
	}
	
	

	protected EB_0000_ObjectMap_HelperHelper()
	{
		setScriptName("TestScripts.EB_0000_ObjectMap_Helper");
	}
	
}

