// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts;
import FuncLib.HelpUtil;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>EB_0000_ObjectMap_Helper</b><br>
 * Generated     : <b>2011/08/25 12:39:54 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  August 25, 2011
 * @author 281MGOTT
 */
public abstract class EB_0000_ObjectMap_HelperHelper extends FuncLib.HelpUtil
{
	/**
	 * HtmlDialog: with default state.
	 *		.class : Html.Dialog
	 * 		.caption : Security Information
	 */
	public TopLevelTestObject Dialog_SecurityInfo() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("Dialog_SecurityInfo"));
	}
	/**
	 * HtmlDialog: with specific test context and state.
	 *		.class : Html.Dialog
	 * 		.caption : Security Information
	 */
	public TopLevelTestObject Dialog_SecurityInfo(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("Dialog_SecurityInfo"), anchor, flags);
	}
	
	/**
	 * LogOnsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log On
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_logOnsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logOnsubmit"));
	}
	/**
	 * LogOnsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log On
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_logOnsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logOnsubmit"), anchor, flags);
	}
	
	/**
	 * Loginbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Login
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_loginbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_loginbutton"));
	}
	/**
	 * Loginbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Login
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_loginbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_loginbutton"), anchor, flags);
	}
	
	/**
	 * Logoutbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Logout
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logout"));
	}
	/**
	 * Logoutbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Logout
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject button_logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logout"), anchor, flags);
	}
	
	/**
	 * HtmlDialogButtonYes: with default state.
	 *		.text : &Yes
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 0
	 */
	public GuiTestObject dialog_htmlDialogButtonYes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("dialog_htmlDialogButtonYes"));
	}
	/**
	 * HtmlDialogButtonYes: with specific test context and state.
	 *		.text : &Yes
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 0
	 */
	public GuiTestObject dialog_htmlDialogButtonYes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("dialog_htmlDialogButtonYes"), anchor, flags);
	}
	
	/**
	 * eBenefitsApply: with default state.
	 *		.title : RegularExpression(eBenefits.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://.*.va\.gov/ebenefits-portal.*)
	 */
	public DocumentTestObject document_eBenefitsHome() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_eBenefitsHome"));
	}
	/**
	 * eBenefitsApply: with specific test context and state.
	 *		.title : RegularExpression(eBenefits.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://.*.va\.gov/ebenefits-portal.*)
	 */
	public DocumentTestObject document_eBenefitsHome(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_eBenefitsHome"), anchor, flags);
	}
	
	/**
	 * welcome: with default state.
	 *		.id : welcome
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_welcomeTag() 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_welcomeTag"));
	}
	/**
	 * welcome: with specific test context and state.
	 *		.id : welcome
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	public GuiTestObject lbl_welcomeTag(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("lbl_welcomeTag"), anchor, flags);
	}
	
	/**
	 * About: with default state.
	 *		.text : About
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_about() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_about"));
	}
	/**
	 * About: with specific test context and state.
	 *		.text : About
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_about(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_about"), anchor, flags);
	}
	
	/**
	 * AboutBenefitsLinks: with default state.
	 *		.text : About Benefits Links
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_aboutBenefitsLinks() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_aboutBenefitsLinks"));
	}
	/**
	 * AboutBenefitsLinks: with specific test context and state.
	 *		.text : About Benefits Links
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_aboutBenefitsLinks(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_aboutBenefitsLinks"), anchor, flags);
	}
	
	/**
	 * ApplyForBenefits: with default state.
	 *		.text : Apply for Benefits
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal;EBEN_JSESSIONID=2 ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_applyForBenefits() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_applyForBenefits"));
	}
	/**
	 * ApplyForBenefits: with specific test context and state.
	 *		.text : Apply for Benefits
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal;EBEN_JSESSIONID=2 ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_applyForBenefits(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_applyForBenefits"), anchor, flags);
	}
	
	/**
	 * Assistance: with default state.
	 *		.text : Assistance
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 12
	 */
	public GuiTestObject link_assistance() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_assistance"));
	}
	/**
	 * Assistance: with specific test context and state.
	 *		.text : Assistance
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 12
	 */
	public GuiTestObject link_assistance(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_assistance"), anchor, flags);
	}
	
	/**
	 * BenefitsByState: with default state.
	 *		.text : Benefits By State
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_benefitsByState() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_benefitsByState"));
	}
	/**
	 * BenefitsByState: with specific test context and state.
	 *		.text : Benefits By State
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_benefitsByState(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_benefitsByState"), anchor, flags);
	}
	
	/**
	 * BrowseBenefitsLinks: with default state.
	 *		.text : Browse Benefits Links
	 * 		.id : 
	 * 		.href : https://.*.va\.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=false&_pag ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	public GuiTestObject link_browseBenefitsLinks() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_browseBenefitsLinks"));
	}
	/**
	 * BrowseBenefitsLinks: with specific test context and state.
	 *		.text : Browse Benefits Links
	 * 		.id : 
	 * 		.href : https://.*.va\.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr=false&_pag ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	public GuiTestObject link_browseBenefitsLinks(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_browseBenefitsLinks"), anchor, flags);
	}
	
	/**
	 * Compensation: with default state.
	 *		.text : Compensation
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	public GuiTestObject link_compensation() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_compensation"));
	}
	/**
	 * Compensation: with specific test context and state.
	 *		.text : Compensation
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	public GuiTestObject link_compensation(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_compensation"), anchor, flags);
	}
	
	/**
	 * Contact: with default state.
	 *		.text : Contact
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	public GuiTestObject link_contact() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_contact"));
	}
	/**
	 * Contact: with specific test context and state.
	 *		.text : Contact
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	public GuiTestObject link_contact(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_contact"), anchor, flags);
	}
	
	/**
	 * Death: with default state.
	 *		.text : Death
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	public GuiTestObject link_death() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_death"));
	}
	/**
	 * Death: with specific test context and state.
	 *		.text : Death
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	public GuiTestObject link_death(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_death"), anchor, flags);
	}
	
	/**
	 * Education: with default state.
	 *		.text : Education
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	public GuiTestObject link_education() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_education"));
	}
	/**
	 * Education: with specific test context and state.
	 *		.text : Education
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	public GuiTestObject link_education(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_education"), anchor, flags);
	}
	
	/**
	 * Employment: with default state.
	 *		.text : Employment
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	public GuiTestObject link_employment() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_employment"));
	}
	/**
	 * Employment: with specific test context and state.
	 *		.text : Employment
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	public GuiTestObject link_employment(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_employment"), anchor, flags);
	}
	
	/**
	 * FacilityLocator: with default state.
	 *		.text : Facility Locator
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	public GuiTestObject link_facilityLocator() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_facilityLocator"));
	}
	/**
	 * FacilityLocator: with specific test context and state.
	 *		.text : Facility Locator
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	public GuiTestObject link_facilityLocator(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_facilityLocator"), anchor, flags);
	}
	
	/**
	 * FeatureList: with default state.
	 *		.text : Feature List
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/contact.html
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	public GuiTestObject link_featureList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_featureList"));
	}
	/**
	 * FeatureList: with specific test context and state.
	 *		.text : Feature List
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/contact.html
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	public GuiTestObject link_featureList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_featureList"), anchor, flags);
	}
	
	/**
	 * FinancialServices: with default state.
	 *		.text : Financial Services
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	public GuiTestObject link_financialServices() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_financialServices"));
	}
	/**
	 * FinancialServices: with specific test context and state.
	 *		.text : Financial Services
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	public GuiTestObject link_financialServices(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_financialServices"), anchor, flags);
	}
	
	/**
	 * Health: with default state.
	 *		.text : Health
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	public GuiTestObject link_health() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_health"));
	}
	/**
	 * Health: with specific test context and state.
	 *		.text : Health
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	public GuiTestObject link_health(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_health"), anchor, flags);
	}
	
	/**
	 * Help: with default state.
	 *		.text : Help
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	public GuiTestObject link_help() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_help"));
	}
	/**
	 * Help: with specific test context and state.
	 *		.text : Help
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	public GuiTestObject link_help(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_help"), anchor, flags);
	}
	
	/**
	 * Home: with default state.
	 *		.text : Home
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_home() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_home"));
	}
	/**
	 * Home: with specific test context and state.
	 *		.text : Home
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject link_home(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_home"), anchor, flags);
	}
	
	/**
	 * Housing: with default state.
	 *		.text : Housing
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	public GuiTestObject link_housing() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_housing"));
	}
	/**
	 * Housing: with specific test context and state.
	 *		.text : Housing
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	public GuiTestObject link_housing(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_housing"), anchor, flags);
	}
	
	/**
	 * IAmA: with default state.
	 *		.text : I Am a ...
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/i_am.html
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	public GuiTestObject link_iAmA() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_iAmA"));
	}
	/**
	 * IAmA: with specific test context and state.
	 *		.text : I Am a ...
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/i_am.html
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	public GuiTestObject link_iAmA(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_iAmA"), anchor, flags);
	}
	
	/**
	 * Insurance: with default state.
	 *		.text : Insurance
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 9
	 */
	public GuiTestObject link_insurance() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_insurance"));
	}
	/**
	 * Insurance: with specific test context and state.
	 *		.text : Insurance
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 9
	 */
	public GuiTestObject link_insurance(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_insurance"), anchor, flags);
	}
	
	/**
	 * Retirement: with default state.
	 *		.text : Retirement
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 10
	 */
	public GuiTestObject link_retirement() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_retirement"));
	}
	/**
	 * Retirement: with specific test context and state.
	 *		.text : Retirement
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 10
	 */
	public GuiTestObject link_retirement(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_retirement"), anchor, flags);
	}
	
	/**
	 * Transition: with default state.
	 *		.text : Transition
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 11
	 */
	public GuiTestObject link_transition() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_transition"));
	}
	/**
	 * Transition: with specific test context and state.
	 *		.text : Transition
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 11
	 */
	public GuiTestObject link_transition(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_transition"), anchor, flags);
	}
	
	/**
	 * TravelTransportation: with default state.
	 *		.text : Travel & Transportation
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 13
	 */
	public GuiTestObject link_travelTransportation() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_travelTransportation"));
	}
	/**
	 * TravelTransportation: with specific test context and state.
	 *		.text : Travel & Transportation
	 * 		.id : 
	 * 		.href : https://vaebnweb2.aac.va.gov/ebenefits-portal/ebenefits.portal?_nfpb=true&_nfxr= ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 13
	 */
	public GuiTestObject link_travelTransportation(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_travelTransportation"), anchor, flags);
	}
	
	/**
	 * ViewMyStatus: with default state.
	 *		.text : View my Status
	 * 		.id : 
	 * 		.href : javascript:bea.wlp.disc.xie._Service.update('https://vaebnweb2.aac.va.gov/ebenef ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_viewMyStatus() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewMyStatus"));
	}
	/**
	 * ViewMyStatus: with specific test context and state.
	 *		.text : View my Status
	 * 		.id : 
	 * 		.href : javascript:bea.wlp.disc.xie._Service.update('https://vaebnweb2.aac.va.gov/ebenef ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject link_viewMyStatus(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewMyStatus"), anchor, flags);
	}
	
	/**
	 * famId: with default state.
	 *		.id : famId
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : famId
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_LogInID() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_LogInID"));
	}
	/**
	 * famId: with specific test context and state.
	 *		.id : famId
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : famId
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_LogInID(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_LogInID"), anchor, flags);
	}
	
	/**
	 * pwd: with default state.
	 *		.id : pwd
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_pwd() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"));
	}
	/**
	 * pwd: with specific test context and state.
	 *		.id : pwd
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject text_pwd(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"), anchor, flags);
	}
	
	

	protected EB_0000_ObjectMap_HelperHelper()
	{
		setScriptName("TestScripts.EB_0000_ObjectMap_Helper");
	}
	
}

